configs:

  addNodeJsAppRunner:
    appIcon: üê∏

  makeNodeJsAppRunner:
    _prepareVariables: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/nodeJsAppRunner/bash/prepareVariables.sh"
    defaultNodeJsAppPorts: |
      [
        "3000"
      ]
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/_task/appRunner/_base/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/_task/appRunner/native/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/NodeJsAppRunner/appRunnerTemplate"
      ]
  