includes:
  - ./config.zaruba.yaml
  - ./env.zaruba.yaml
  - ./input.zaruba.yaml

tasks:

  runZarubaServiceName:
    icon: üçù
    extend: core.startDockerContainer
    dependencies:
      - pullZarubaServiceNameImage
    timeout: 1h
    inputs:
      - zarubaServiceNameRunInLocal
    config:
      afterCheck: sleep 15
      runInLocal: '{{ .GetValue "zarubaServiceNameRunInLocal" }}'
    configRef: zarubaServiceName
    envRef: zarubaServiceName

  pullZarubaServiceNameImage:
    extend: core.pullDockerImage
    timeout: 1h
    configRef: zarubaServiceName

  stopZarubaServiceNameContainer:
    extend: core.stopDockerContainer
    configRef: zarubaServiceName

  removeZarubaServiceNameContainer:
    extend: core.removeDockerContainer
    configRef: zarubaServiceName