env:
  REDIS_PORT: 6479

components: 
  redis:
    symbol: ğŸ®
    type: container
    image: redis
    ports:
      ${REDIS_PORT}: 6379

    # [ğŸ’€ NOTE] Uncomment the following 2 lines if you want to use volume
    # volumes:
    #   ./redis-volume: /data