configs:

  makeHelmDeploymentTask:
    _skipCreationPath: 'zaruba-tasks/${_ZRB_DEPLOYMENT_NAME}'
    _taskIndexPath: './zaruba-tasks/${_ZRB_DEPLOYMENT_NAME}/index.yaml'
    _registerAppRunnerTasks: ''
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/appHelmDeployment/deploymentTaskTemplate"
      ]