configs:

  makeDockerContainerAppRunner:
    appIcon: ğŸ³
    _nativePrepareAppRunnerTaskName: ''
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/_base/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/dockerContainer/template"
      ]
    defaultAppDirectory: '{{ .ProjectName }}Docker'
    defaultAppPorts: |
      [
        "8080"
      ]