includes:
  - ./config.zaruba.yaml
  - ./env.zaruba.yaml
  - ./input.zaruba.yaml
  - ./taskHelm.zaruba.yaml

tasks:

  runZarubaServiceName:
    icon: ðŸ§°
    extend: zrbStartDockerContainer
    dependencies:
      - pullZarubaServiceNameImage
    timeout: 1h
    inputs:
      - zarubaServiceNameRunInLocal
    config:
      runInLocal: '{{ .GetValue "zarubaServiceNameRunInLocal" }}'
    configRef: zarubaServiceName
    envRef: zarubaServiceName
 
  flushZarubaServiceName:
    icon: ðŸ§°
    extend: zrbRunInDockerContainer
    dependencies:
      - runZarubaServiceName
    configRef: zarubaServiceName
    config:
      commands: redis-cli flushall

  pullZarubaServiceNameImage:
    extend: zrbPullDockerImage
    timeout: 1h
    configRef: zarubaServiceName

  stopZarubaServiceNameContainer:
    extend: zrbStopDockerContainer
    configRef: zarubaServiceName

  removeZarubaServiceNameContainer:
    extend: zrbRemoveDockerContainer
    configRef: zarubaServiceName