tasks:

  zrbPreparePythonApp:
    icon: ğŸ
    description: Prepare Python App
    private: true
    extend: zrbRunShellScript
    config:
      _start: pipenv install
      start: "echo Prepare Python App"

