components: 

  redisGlobal:
    symbol: ğŸ®
    type: container
    image: redis
    ports:
      6379: 6379
    volumes:
      ./volume: /data

  redisCommander:
    symbol: ğŸ®
    type: container
    image: rediscommander/redis-commander
    env:
      REDIS_HOSTS: local:${redisGlobal}:6379
    ports:
      8093: 8081 
    dependencies:
      - redisGlobal
    readinessCheck: curl localhost:8093
