components: 

  redis:
    symbol: ğŸ®
    type: container
    image: redis
    ports:
      6379: 6379
    # volumes:
    #   ./volume: /data

  # rediscmder:
  #   symbol: ğŸ®
  #   type: container
  #   image: rediscommander/redis-commander
  #   env:
  #     REDIS_HOSTS: local:${redis}:6379
  #   ports:
  #     8081: 8081 
  #   dependencies:
  #     - redis
  #   readinessUrl: http://localhost:8081
