configs:

  addPythonAppRunner:
    appIcon: üêç

  makePythonAppRunner:
    _prepareVariables: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/pythonAppRunner/bash/prepareVariables.sh"
    defaultPythonAppPorts: |
      [
        "3000"
      ]
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/_task/appRunner/_base/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/_task/appRunner/native/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/pythonAppRunner/appRunnerTemplate"
      ]
  