tasks:

  clearPreviousValues:
    icon: ðŸ”¥
    description: |
      Clear log
    extend: zrbRunCoreScript
    configs:
      start: |
        {{ $d := .Decoration -}}
        rm -Rf .previous.values.yaml
        echo "{{ $d.Bold }}{{ $d.Yellow }}Previous values removed{{ $d.Normal }}"