tasks:

  makeDockerAppRunner:
    icon: ğŸ³
    extend: zrbMakeAppRunner
    inputs:
      - appDirectory
      - appDependencies
      - appName
      - appImageName
      - appContainerName
      - appEnvs
      - appPorts
    configs:
      templateLocations: |
        [
          "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/_base/template",
          "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/docker/template"
        ]