tasks:

  makeDockerHelmTask:
    icon: ğŸ³
    extend: zrbMakeHelmTask
    dependencies:
      - makeDockerHelm
      - makeDockerAppRunner
    inputs:
      - appDirectory
      - appName
      - deploymentDirectory
      - deploymentName
    configRefs:
      - addDocker
