tasks:

  makeDockerHelmTask:
    icon: ğŸ³
    extend: zrbMakeHelmTask
    dependencies:
      - makeDockerHelm
      - makeDockerAppRunner
    inputs:
      - appDirectory
      - appName
      - appHelmDirectory
      - appHelmReleaseName
    configRefs:
      - addDocker
