tasks:
  runZarubaServiceName:
    icon: ğŸ³
    extend: core.startDockerContainer
    timeout: 1h

configs:
  zarubaServiceName:
    useImagePrefix: false
    imageName: zarubaImageName
    containerName: zarubaContainerName
    expose: lconfig.ports