tasks:

  zarubaRunTask:
    icon: ğŸ³
    extend: core.startDockerContainer
    timeout: 1h
    env: {}
    config:
      useImagePrefix: false
      imageName: zarubaImageName
      containerName: zarubaContainerName