inputs:

  zarubaServiceNameRunInLocal: {}

tasks:

  pullZarubaServiceNameImage: {}

  runZarubaServiceName:
    icon: üçù
    extend: core.startDockerContainer
    dependencies:
    - pullZarubaServiceNameImage
    timeout: 1h
    inputs:
    - zarubaServiceNameRunInLocal
    config:
      afterCheck: sleep 15

configs:
  zarubaServiceName:
    imagePrefix: docker.elastic.co/elasticsearch
    imageName: elasticsearch
    imageTag: 7.1.1
    containerName: zarubaContainerName
    ports: |
      9200
      9300

envs:
  zarubaServiceName:
    discovery.type:
      from: ES_DISCOVER_TYPE
      default: single-node
    ES_JAVA_OPTS:
      from: ES_JAVA_OPTS
      default: "-Xms512m -Xmx512m"
        