inputs:

  zarubaServiceNameRunInLocal: {}

tasks:

  pullZarubaServiceNameImage: {}

  runZarubaServiceName:
    icon: üçÉ
    extend: core.startDockerContainer
    dependencies:
    - pullZarubaServiceNameImage
    timeout: 1h
    inputs:
    - zarubaServiceNameRunInLocal

configs:
  zarubaServiceName:
    useImagePrefix: false
    imageName: mongo
    containerName: zarubaContainerName
    ports: 27017

envs:
  zarubaServiceName:
    MONGO_INITDB_ROOT_USERNAME:
      from: MONGO_INITDB_ROOT_USERNAME
      default: root
    MONGO_INITDB_ROOT_PASSWORD:
      from: MONGO_INITDB_ROOT_PASSWORD
      default: toor