inputs:

  zarubaServiceName.runLocally: {}

  zarubaServiceName.sql:
    validation: ^.+$
    prompt: single line SQL to be executed (Required)
    description: single line SQL to be executed

tasks:

  pullZarubaServiceNameImage: {}

  runZarubaServiceName:
    icon: üê¨ 
    extend: core.mysql.startDockerContainer
    dependencies:
    - pullZarubaServiceNameImage
    timeout: 1h
    inputs:
    - zarubaServiceName.runLocally
    config:
      afterCheck: sleep 3

  zarubaServiceNameExecSql:
    icon: üê¨ 
    extend: core.mysql.execSql
    dependencies:
    - runZarubaServiceName
    inputs:
    - zarubaServiceName.sql
    envRef: zarubaServiceName
    configRef: zarubaServiceName
    config:
      queries: '{{ .GetValue "zarubaServiceName.sql" }}'

configs:
  zarubaServiceName:
    useImagePrefix: false
    imageName: mysql
    containerName: zarubaContainerName
    port::3306: 3306
    expose: config.port

envs:
  zarubaServiceName:
    MYSQL_USER:
      from: MYSQL_USER
      default: mysql
    MYSQL_PASSWORD:
      from: MYSQL_PASSWORD
      default: mysql
    MYSQL_ROOT_PASSWORD:
      from: MYSQL_ROOT_PASSWORD
      default: toor
    MYSQL_DATABASE:
      from: MYSQL_DATABASE
      default: sample