tasks:

  runZarubaServiceName:
    icon: üêá
    extend: core.startDockerContainer
    timeout: 1h
    config:
      afterCheck: |
        set +e
        docker exec "${CONTAINER_NAME}" rabbitmqctl await_startup
        until [ "$?" = "0" ]
        do
          docker exec "${CONTAINER_NAME}" rabbitmqctl await_startup
          sleep 3
        done
  
  resetZarubaServiceName:
    icon: üêá
    extend: core.runShellScript
    dependencies:
    - runZarubaServiceName
    configRef: zarubaServiceName
    config:
      start: |
        docker exec {{ .GetConfig "containerName" }} rabbitmqctl stop_app
        docker exec {{ .GetConfig "containerName" }} rabbitmqctl reset
        docker exec {{ .GetConfig "containerName" }} rabbitmqctl start_app

configs:
  zarubaServiceName:
    useImagePrefix: false
    imageName: rabbitmq
    imageTag: 3-management
    containerName: zarubaContainerName
    port::5672: 5672
    port::15672: 15672
    expose: config.port

envs:
  zarubaServiceName:
    RABBITMQ_DEFAULT_USER:
      from: RABITMQ_DEFAULT_USER
      default: root
    RABBITMQ_DEFAULT_PASS:
      from: RABITMQ_DEFAULT_PASS
      default: toor