tasks:

  runZarubaServiceName:
    icon: ğŸ§°
    extend: core.startDockerContainer
    timeout: 1h
 
  flushZarubaServiceName:
    icon: ğŸ‡
    extend: core.runShellScript
    dependencies:
    - runZarubaServiceName
    configRef: zarubaServiceName
    config:
      start: |
        docker exec {{ .GetConfig "containerName" }} redis-cli flushall

configs:
  zarubaServiceName:
    useImagePrefix: false
    imageName: redis
    containerName: zarubaContainerName
    port::6379: 6379
    expose: config.port