tasks:

  core.runShellScript:
    icon: ğŸš
    description: |
      Run shell script
      Common config:
        start : Start script
    private: true
    extend: core.runScript
    config:
      start: "echo hello world"