tasks:
     
  core.postgre.execSql:
    icon: üê¨ 
    private: true
    extend: core.runCoreScript
    configRef: coreDocker
    config:
      user: '{{ .GetEnv "POSTGRES_USER" }}'
      password: '{{ .GetEnv "POSTGRES_PASSWORD" }}'
      database: '{{ .GetEnv "POSTGRES_DB" }}'
      queries: ""
      containerName: ""
      _start: |
        {{ $localTmpFile := printf "%s.tmp.sql" .NewUUIDString -}}
        {{ $err := .WriteFile $localTmpFile (.GetConfig "queries") -}}
        USER="{{ .GetConfig "user" }}"
        PASSWORD="{{ .GetConfig "password" }}"
        CONTAINER_NAME="{{ .GetConfig "containerName" }}"
        LOCAL_TMP_FILE="{{ $localTmpFile }}"
        CONTAINER_TMP_FILE="/{{ .NewUUIDString }}.tmp.sql"
        docker cp "${LOCAL_TMP_FILE}" "${CONTAINER_NAME}:${CONTAINER_TMP_FILE}"
        rm "${LOCAL_TMP_FILE}"
        docker exec "${CONTAINER_NAME}" bash -c "psql --user=${USER} -w --file=${CONTAINER_TMP_FILE}"
        docker exec "${CONTAINER_NAME}" rm "${CONTAINER_TMP_FILE}"
      start: ""

