tasks: 

  makeFastApiEventHandler:
    icon: âš¡
    description: Make FastAPI event handler
    inputs:
      - fastApiServiceName
      - fastApiModuleName
      - fastApiEventName
    extend: core.runCoreScript
    dependencies:
      - core.showAdv
    configRef: generatorFastApi
    config:
      eventName: '{{ .GetValue "fastApiEventName" }}'
      start: |
        {{- $d := .Decoration -}}
        MODULE_TEMPLATE_LOCATION={{ .EscapeShellArg (.GetConfig "moduleTemplateLocation") }}
        SERVICE_TEMPLATE_LOCATION={{ .EscapeShellArg (.GetConfig "serviceTemplateLocation") }}
        TASK_TEMPLATE_LOCATION={{ .EscapeShellArg (.GetConfig "taskTemplateLocation") }}
        SERVICE_NAME={{ .EscapeShellArg (.GetConfig "serviceName") }}
        MODULE_NAME={{ .EscapeShellArg (.GetConfig "moduleName") }}
        EVENT_NAME={{ .EscapeShellArg (.GetConfig "eventName") }}
        . ${ZARUBA_HOME}/bash/generateFastApiEventHandler.sh
        generateFastApiEventHandler \
          "${MODULE_TEMPLATE_LOCATION}" \
          "${SERVICE_TEMPLATE_LOCATION}" \
          "${TASK_TEMPLATE_LOCATION}" \
          "${SERVICE_NAME}" \
          "${MODULE_NAME}" \
          "${EVENT_NAME}"
        echo ðŸŽ‰ðŸŽ‰ðŸŽ‰
        echo "{{ $d.Bold }}{{ $d.Yellow }}Fast API event handler created: ${EVENT_NAME} on ${SERVICE_NAME}/${MODULE_NAME}{{ $d.Normal }}"
        echo "You probably need to check the following files:"
        echo "- ${SERVICE_NAME}/main.py"
        echo "- ${SERVICE_NAME}/${MODULE_NAME}/controller.py"

