tasks:
    
  makeDockerTask:
    icon: ğŸ³
    extend: core.makeDockerTask
    inputs:
      - generatorDockerImageName
      - generatorDockerContainerName
      - generatorServiceName
      - generatorServiceEnvs
      - generatorServicePorts
      - generatorTaskDependencies
  

