tasks:
    
  makeDockerTask:
    icon: ğŸ³
    extend: core.makeDockerTask
    inputs:
      - dockerImageName
      - dockerContainerName
      - newServiceName
      - newServiceEnvs
      - newServicePorts
      - newTaskDependencies
  

