tasks:
    
  makeDockerTask:
    icon: ğŸ³
    extend: core.makeDockerTask
    inputs:
      - dockerImageName
      - dockerContainerName
      - serviceName
      - serviceEnvs
      - servicePorts
      - taskDependencies
  

