tasks:

  serveHttp:
    icon: üåê
    description: |
      Run static web server from your working directory.
    extend: core.startService
    inputs:
      - serverHttpPort
    config:
      ports: '{{ .GetValue "serverHttpPort" }}'
    start: 
      - '{{ .GetEnv "ZARUBA_HOME" }}/zaruba'
      - serve
      - .
      - '{{ index (.Util.Str.Split (.Util.Str.Trim (.GetConfig "ports") "\n ") "\n") 0 }}'