tasks:

  serveHttp:
    icon: ğŸŒ
    description: |
      Run static web server from your working directory.
    extend: core.startService
    inputs:
      - serverHttpPort
    config:
      ports: '{{ .GetValue "serverHttpPort" }}'
    start: 
      - '{{ .GetEnv "ZARUBA_HOME" }}/zaruba'
      - util serve
      - .
      - '{{ index (.Split (.Trim (.GetConfig "ports") "\n ") "\n") 0 }}'