tasks:

  setProjectValue:
    icon: ðŸ”—
    description: Set project value.
    extend: core.runCoreScript
    dependencies:
      - core.isProject
    inputs:
      - variableName
      - variableValue
    config:
      variableName: '{{ .GetValue "variableName" }}'
      variableValue: '{{ .GetValue "variableValue" }}'
      start: |
        {{ $d := .Decoration -}}
        "{{ .ZarubaBin }}" project setValue "{{ .GetWorkPath "default.values.yaml" }}" "{{ .GetConfig "variableName" }}" "{{ .GetConfig "variableValue" }}"
        echo ðŸŽ‰ðŸŽ‰ðŸŽ‰
        echo "{{ $d.Bold }}{{ $d.Yellow }}Kwarg ${KEY} : ${VALUE} has been set{{ $d.Normal }}"

