tasks:

  setupTmux:
    icon: ğŸ”¨
    description: setup tmux (tmux should be already installed before running this task)
    extend: core.runCoreScript
    timeout: 1h
    inputs:
    - setupHomeDir
    config:
      beforeStart: |
        {{ $d := .Decoration -}}
        echo "This command will setup tmux. Tmux should be installed first"
        echo "If this command doesn't run successfully, please open an issue on https://github.com/state-alcemists/zaruba."
        echo "Please also specify your OS version."
      start: |
        {{ $d := .Decoration -}}
        {{ if .GetValue "setupHomeDir" }}HOME="{{ .GetValue "setupHomeDir" }}"{{ end }}
        if [ "$(is_command_exist tmux -V)" = 1 ]
        then
          echo "ğŸ‘ {{ $d.Bold }}{{ $d.Yellow }}Tmux was already installed{{ $d.Normal }}"
        else
          echo "{{ $d.Bold }}{{ $d.Red }}Tmux was not installed. Please install tmux first{{ $d.Normal }}"
          exit 1
        fi
        if [ -d "${HOME}/.tmux/plugins/tpm" ]
        then
          echo "ğŸ‘ {{ $d.Bold }}{{ $d.Yellow }}Tmux plugin was already installed{{ $d.Normal }}"
        else
          git clone https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"
        fi
        if [ -f "${HOME}/.tmux.conf" ]
        then
          mv "${HOME}/.tmux.conf" "${HOME}/.tmux.bak.conf"
        fi
        cp "${ZARUBA_HOME}/scripts/templates/tmux.conf" "${HOME}/.tmux.conf"
        echo ğŸ‰ğŸ‰ğŸ‰
        echo "{{ $d.Bold }}{{ $d.Yellow }}Complete !!!{{ $d.Normal }}"

