tasks:

  zrbRunShellScript:
    icon: ğŸš
    description: |
      Run shell script
      Common config:
        start : Start script
    private: true
    extend: zrbRunScript
    config:
      start: "echo hello world"