name: PROJECT NAME
env: 
  RABBITMQ_DEFAULT_USER: root
  RABBITMQ_DEFAULT_PASS: toor

components: 
  rmq:
    symbol: üêá 
    type: container
    image: rabbitmq:3-management
    ports: 
        5672: 5672
        8091: 15672
    readinessCheck: sleep 1 && curl localhost:8091 
