name: testRun
env: 
  RMQ_HOST: ${rmq}
  RMQ_PORT: 5672
  RMQ_USER: root
  RMQ_PASSWORD: toor
  RMQ_VHOST: /

components: 
  rmq:
    type: container
    image: rabbitmq:3-management
    env:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    ports: 
        5672: 5672   # host: container
        15672: 15672
    readinessCheck: curl ${rmq}:15672