env: 
  RABBITMQ_DEFAULT_USER: root
  RABBITMQ_DEFAULT_PASS: toor
  DEFAULT_RMQ_CONNECTION_STRING: amqp://root:toor@{rmq}:5672/

components: 
  rmq:
    symbol: üêá 
    type: container
    image: rabbitmq:3-management
    env:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports: 
        5672: 5672
        15672: 15672
    readinessUrl: http://localhost:15672 
